- hosts: localhost
  gather_facts: false
  environment:
    - ANSIBLE_INVENTORY_ENABLED: 'ini'
  tasks:
    - command: "ansible -i /etc/ansible/hosts all --list-hosts -vvvv"
  
    - name: test
      debug:
        msg: andrew-cowan.ubvm.nutanix.com

    - name: Creating a file with content
      copy:
      dest: "inventory"
      content: |
        andrew-cowan.ubvm.nutanix.com
...
