---
- hosts: localhost
  gather_facts: false
  environment:
    - ANSIBLE_INVENTORY_ENABLED: 'ini'
  tasks:
    # - command: "ansible -i /etc/ansible/hosts all --list-hosts -vvvv"
  
    - name: test
      debug:
        msg: ian-cowan.ubvm.nutanix.com

    - name: Creating a file with content
      copy:
        dest: "/var/lib/awx/projects/*create_inv_from_playbook/hosts"
        mode: "0644"
        content: |
          fred-cowan.ubvm.nutanix.com
          andrew-cowan.ubvm.nutanix.com ansible_python_interpreter=/usr/bin/python3
...
